# Generated by Django 4.2.3 on 2023-08-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
